// create a product andthe information it will contains here
const data = {
  products: [
    {
      name: 'Nike sandals',
      slug: 'Nike sandals',
      categpry: 'Sandals',
      image: '/images/p1.jpeg',
      price: 150,
      countInStock: 18,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality nike sandals',
    },
    {
      name: 'Nike sandals',
      slug: 'Nice sandals',
      categpry: 'Sandals',
      image: '/images/p2.jpeg',
      price: 150,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality nike sandals',
    },
    {
      name: 'Nike sandals',
      slug: 'Nike nice cross sandals',
      categpry: 'Sandals',
      image: '/images/p3.jpeg',
      price: 150,
      countInStock: 11,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality nike sandals',
    },
    {
      name: 'Nike sandals',
      slug: 'Nike cross sandals',
      categpry: 'Sandals',
      image: '/images/p4.jpeg',
      price: 150,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality nike sandals',
    },
    {
      name: 'Nike sandals',
      slug: 'Cross sandals',
      categpry: 'Sandals',
      image: '/images/p5.jpeg',
      price: 150,
      countInStock: 9,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality nike sandals',
    },
    {
      name: 'Nike cross',
      slug: 'Nike nice sandals',
      categpry: 'Sandals',
      image: '/images/p6.jpeg',
      price: 150,
      countInStock: 25,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality nike sandals',
    },
    {
      name: 'Nike sandals',
      slug: 'Nice nike sandals',
      categpry: 'Sandals',
      image: '/images/p7.jpeg',
      price: 150,
      countInStock: 20,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality nike sandals',
    },
    {
      name: 'Nike sandals',
      slug: 'Cross nice sandals',
      categpry: 'Sandals',
      image: '/images/p8.jpeg',
      price: 150,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality nike sandals',
    },
  ],
};

export default data;
