const data = {
  products: [
    {
      name: 'Shoe',
      slug: 'Original Shoe1',
      category: 'Shoes',
      image: '/images/p1.jpg',
      price: 150,
      countInStock: 20,
      brand: 'Nike',
      rating: 5.5,
      numReviews: 10,
      description: 'High quality shirts',
    },
    {
      name: 'Shoe',
      slug: 'Original Shoe2',
      category: 'Shoes',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 30,
      brand: 'Nike',
      rating: 5.5,
      numReviews: 10,
      description: 'High quality Sandals',
    },
    {
      name: 'Sandals',
      slug: 'Original Sandals3',
      category: 'Sandals',
      image: '/images/p3.jpg',
      price: 115,
      countInStock: 15,
      brand: 'Birken Stock',
      rating: 5.5,
      numReviews: 10,
      description: 'High quality Sandals',
    },
    {
      name: 'Birk Sandals',
      slug: 'Original Sandals4',
      category: 'Sandals',
      image: '/images/p4.jpg', //679px 829px
      price: 115,
      countInStock: 30,
      brand: 'Birken Stock',
      rating: 5.5,
      numReviews: 10,
      description: 'High quality Sandals',
    },
    {
      name: 'Birk Sandals',
      slug: 'Original Sandals5',
      category: 'Sandals',
      image: '/images/p5.jpg',
      price: 115,
      countInStock: 30,
      brand: 'Birken Stock',
      rating: 5.5,
      numReviews: 10,
      description: 'High quality Sandals',
    },
  ],
};

export default data;
